name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }})
    strategy:
      matrix:
        ruby:
          - '3.3'
          - '3.4'
          - '4.0'
        os:
          - ubuntu-latest
          - macos-latest

    env:
      WASVAL_RUBY_CWASM_PATH: /tmp/ruby.cwasm
      WASVAL_RUBY_VERSION: 3.4

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install ruby.wasm
        run: bundle exec ruby -e "require 'wasval'; Wasval::Install::RubyWasm.new.install"
      - name: Run the default task
        run: bundle exec rake
